/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingoti.Client.OpenAPIDateConverter;

namespace Fingoti.Model
{
    /// <summary>
    /// ClaimRequest
    /// </summary>
    [DataContract(Name = "ClaimRequest")]
    public partial class ClaimRequest : IEquatable<ClaimRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClaimRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClaimRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClaimRequest" /> class.
        /// </summary>
        /// <param name="serial">serial (required).</param>
        public ClaimRequest(string serial = default(string))
        {
            // to ensure "serial" is required (not null)
            if (serial == null)
            {
                throw new ArgumentNullException("serial is a required property for ClaimRequest and cannot be null");
            }
            this.Serial = serial;
        }

        /// <summary>
        /// Gets or Sets Serial
        /// </summary>
        [DataMember(Name = "serial", IsRequired = true, EmitDefaultValue = true)]
        public string Serial { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClaimRequest {\n");
            sb.Append("  Serial: ").Append(Serial).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClaimRequest);
        }

        /// <summary>
        /// Returns true if ClaimRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ClaimRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClaimRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Serial == input.Serial ||
                    (this.Serial != null &&
                    this.Serial.Equals(input.Serial))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Serial != null)
                {
                    hashCode = (hashCode * 59) + this.Serial.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
