/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingoti.Client.OpenAPIDateConverter;

namespace Fingoti.Model
{
    /// <summary>
    /// NetworkMac
    /// </summary>
    [DataContract(Name = "NetworkMac")]
    public partial class NetworkMac : IEquatable<NetworkMac>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkMac" /> class.
        /// </summary>
        /// <param name="ap">ap.</param>
        /// <param name="station">station.</param>
        public NetworkMac(string ap = default(string), string station = default(string))
        {
            this.Ap = ap;
            this.Station = station;
        }

        /// <summary>
        /// Gets or Sets Ap
        /// </summary>
        [DataMember(Name = "ap", EmitDefaultValue = true)]
        public string Ap { get; set; }

        /// <summary>
        /// Gets or Sets Station
        /// </summary>
        [DataMember(Name = "station", EmitDefaultValue = true)]
        public string Station { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkMac {\n");
            sb.Append("  Ap: ").Append(Ap).Append("\n");
            sb.Append("  Station: ").Append(Station).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NetworkMac);
        }

        /// <summary>
        /// Returns true if NetworkMac instances are equal
        /// </summary>
        /// <param name="input">Instance of NetworkMac to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NetworkMac input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Ap == input.Ap ||
                    (this.Ap != null &&
                    this.Ap.Equals(input.Ap))
                ) && 
                (
                    this.Station == input.Station ||
                    (this.Station != null &&
                    this.Station.Equals(input.Station))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ap != null)
                {
                    hashCode = (hashCode * 59) + this.Ap.GetHashCode();
                }
                if (this.Station != null)
                {
                    hashCode = (hashCode * 59) + this.Station.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
