/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Fingoti.Client.OpenAPIDateConverter;

namespace Fingoti.Model
{
    /// <summary>
    /// WifiStatus
    /// </summary>
    [DataContract(Name = "WifiStatus")]
    public partial class WifiStatus : IEquatable<WifiStatus>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Slot
        /// </summary>
        [DataMember(Name = "slot", EmitDefaultValue = false)]
        public WifiSlot? Slot { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WifiStatus" /> class.
        /// </summary>
        /// <param name="slot">slot.</param>
        /// <param name="signal">signal.</param>
        public WifiStatus(WifiSlot? slot = default(WifiSlot?), int signal = default(int))
        {
            this.Slot = slot;
            this.Signal = signal;
        }

        /// <summary>
        /// Gets or Sets Signal
        /// </summary>
        [DataMember(Name = "signal", EmitDefaultValue = false)]
        public int Signal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WifiStatus {\n");
            sb.Append("  Slot: ").Append(Slot).Append("\n");
            sb.Append("  Signal: ").Append(Signal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WifiStatus);
        }

        /// <summary>
        /// Returns true if WifiStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of WifiStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WifiStatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Slot == input.Slot ||
                    this.Slot.Equals(input.Slot)
                ) && 
                (
                    this.Signal == input.Signal ||
                    this.Signal.Equals(input.Signal)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Slot.GetHashCode();
                hashCode = (hashCode * 59) + this.Signal.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
