/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing AddWebhookResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddWebhookResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddWebhookResult
        //private AddWebhookResult instance;

        public AddWebhookResultTests()
        {
            // TODO uncomment below to create an instance of AddWebhookResult
            //instance = new AddWebhookResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddWebhookResult
        /// </summary>
        [Fact]
        public void AddWebhookResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddWebhookResult
            //Assert.IsType<AddWebhookResult>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'WebhookNumber'
        /// </summary>
        [Fact]
        public void WebhookNumberTest()
        {
            // TODO unit test for the property 'WebhookNumber'
        }

    }

}
