/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing ClaimedDevicesDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClaimedDevicesDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClaimedDevicesDto
        //private ClaimedDevicesDto instance;

        public ClaimedDevicesDtoTests()
        {
            // TODO uncomment below to create an instance of ClaimedDevicesDto
            //instance = new ClaimedDevicesDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClaimedDevicesDto
        /// </summary>
        [Fact]
        public void ClaimedDevicesDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClaimedDevicesDto
            //Assert.IsType<ClaimedDevicesDto>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Fact]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ClaimPendingCount'
        /// </summary>
        [Fact]
        public void ClaimPendingCountTest()
        {
            // TODO unit test for the property 'ClaimPendingCount'
        }
        /// <summary>
        /// Test the property 'OwnedDeviceCount'
        /// </summary>
        [Fact]
        public void OwnedDeviceCountTest()
        {
            // TODO unit test for the property 'OwnedDeviceCount'
        }
        /// <summary>
        /// Test the property 'OnlineGateways'
        /// </summary>
        [Fact]
        public void OnlineGatewaysTest()
        {
            // TODO unit test for the property 'OnlineGateways'
        }
        /// <summary>
        /// Test the property 'Pebl'
        /// </summary>
        [Fact]
        public void PeblTest()
        {
            // TODO unit test for the property 'Pebl'
        }
        /// <summary>
        /// Test the property 'Vyne'
        /// </summary>
        [Fact]
        public void VyneTest()
        {
            // TODO unit test for the property 'Vyne'
        }

    }

}
