/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceSupport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceSupportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceSupport
        //private DeviceSupport instance;

        public DeviceSupportTests()
        {
            // TODO uncomment below to create an instance of DeviceSupport
            //instance = new DeviceSupport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceSupport
        /// </summary>
        [Fact]
        public void DeviceSupportInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceSupport
            //Assert.IsType<DeviceSupport>(instance);
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
