/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceVersion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceVersionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceVersion
        //private DeviceVersion instance;

        public DeviceVersionTests()
        {
            // TODO uncomment below to create an instance of DeviceVersion
            //instance = new DeviceVersion();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceVersion
        /// </summary>
        [Fact]
        public void DeviceVersionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceVersion
            //Assert.IsType<DeviceVersion>(instance);
        }


        /// <summary>
        /// Test the property 'Hardware'
        /// </summary>
        [Fact]
        public void HardwareTest()
        {
            // TODO unit test for the property 'Hardware'
        }
        /// <summary>
        /// Test the property 'Software'
        /// </summary>
        [Fact]
        public void SoftwareTest()
        {
            // TODO unit test for the property 'Software'
        }

    }

}
