/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceCloud
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceCloudTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceCloud
        //private DeviceCloud instance;

        public DeviceCloudTests()
        {
            // TODO uncomment below to create an instance of DeviceCloud
            //instance = new DeviceCloud();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceCloud
        /// </summary>
        [Fact]
        public void DeviceCloudInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceCloud
            //Assert.IsType<DeviceCloud>(instance);
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Connected'
        /// </summary>
        [Fact]
        public void ConnectedTest()
        {
            // TODO unit test for the property 'Connected'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

    }

}
