/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceRequest
        //private DeviceRequest instance;

        public DeviceRequestTests()
        {
            // TODO uncomment below to create an instance of DeviceRequest
            //instance = new DeviceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceRequest
        /// </summary>
        [Fact]
        public void DeviceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceRequest
            //Assert.IsType<DeviceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'Serial'
        /// </summary>
        [Fact]
        public void SerialTest()
        {
            // TODO unit test for the property 'Serial'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }

    }

}
