/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayWifi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayWifiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayWifi
        //private GatewayWifi instance;

        public GatewayWifiTests()
        {
            // TODO uncomment below to create an instance of GatewayWifi
            //instance = new GatewayWifi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayWifi
        /// </summary>
        [Fact]
        public void GatewayWifiInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayWifi
            //Assert.IsType<GatewayWifi>(instance);
        }


        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Detect'
        /// </summary>
        [Fact]
        public void DetectTest()
        {
            // TODO unit test for the property 'Detect'
        }

    }

}
