/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayNode
        //private GatewayNode instance;

        public GatewayNodeTests()
        {
            // TODO uncomment below to create an instance of GatewayNode
            //instance = new GatewayNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayNode
        /// </summary>
        [Fact]
        public void GatewayNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayNode
            //Assert.IsType<GatewayNode>(instance);
        }


        /// <summary>
        /// Test the property 'Detect'
        /// </summary>
        [Fact]
        public void DetectTest()
        {
            // TODO unit test for the property 'Detect'
        }

    }

}
