/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayUart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayUartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayUart
        //private GatewayUart instance;

        public GatewayUartTests()
        {
            // TODO uncomment below to create an instance of GatewayUart
            //instance = new GatewayUart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayUart
        /// </summary>
        [Fact]
        public void GatewayUartInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayUart
            //Assert.IsType<GatewayUart>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Setup'
        /// </summary>
        [Fact]
        public void SetupTest()
        {
            // TODO unit test for the property 'Setup'
        }
        /// <summary>
        /// Test the property 'Trigger'
        /// </summary>
        [Fact]
        public void TriggerTest()
        {
            // TODO unit test for the property 'Trigger'
        }
        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }

    }

}
