/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing GetProfileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetProfileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetProfileResponse
        //private GetProfileResponse instance;

        public GetProfileResponseTests()
        {
            // TODO uncomment below to create an instance of GetProfileResponse
            //instance = new GetProfileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetProfileResponse
        /// </summary>
        [Fact]
        public void GetProfileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetProfileResponse
            //Assert.IsType<GetProfileResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
        /// <summary>
        /// Test the property 'Forename'
        /// </summary>
        [Fact]
        public void ForenameTest()
        {
            // TODO unit test for the property 'Forename'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'UserHandle'
        /// </summary>
        [Fact]
        public void UserHandleTest()
        {
            // TODO unit test for the property 'UserHandle'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'Marketing'
        /// </summary>
        [Fact]
        public void MarketingTest()
        {
            // TODO unit test for the property 'Marketing'
        }
        /// <summary>
        /// Test the property 'MfaEnabled'
        /// </summary>
        [Fact]
        public void MfaEnabledTest()
        {
            // TODO unit test for the property 'MfaEnabled'
        }
        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }
        /// <summary>
        /// Test the property 'DateRegistered'
        /// </summary>
        [Fact]
        public void DateRegisteredTest()
        {
            // TODO unit test for the property 'DateRegistered'
        }
        /// <summary>
        /// Test the property 'DefaultOrganisation'
        /// </summary>
        [Fact]
        public void DefaultOrganisationTest()
        {
            // TODO unit test for the property 'DefaultOrganisation'
        }
        /// <summary>
        /// Test the property 'LastUsedOrganisation'
        /// </summary>
        [Fact]
        public void LastUsedOrganisationTest()
        {
            // TODO unit test for the property 'LastUsedOrganisation'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
