/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing MqttSetup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MqttSetupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MqttSetup
        //private MqttSetup instance;

        public MqttSetupTests()
        {
            // TODO uncomment below to create an instance of MqttSetup
            //instance = new MqttSetup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MqttSetup
        /// </summary>
        [Fact]
        public void MqttSetupInstanceTest()
        {
            // TODO uncomment below to test "IsType" MqttSetup
            //Assert.IsType<MqttSetup>(instance);
        }


        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Qos'
        /// </summary>
        [Fact]
        public void QosTest()
        {
            // TODO unit test for the property 'Qos'
        }
        /// <summary>
        /// Test the property 'Retain'
        /// </summary>
        [Fact]
        public void RetainTest()
        {
            // TODO unit test for the property 'Retain'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Secure'
        /// </summary>
        [Fact]
        public void SecureTest()
        {
            // TODO unit test for the property 'Secure'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
