/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing MqttDeviceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MqttDeviceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MqttDeviceResponse
        //private MqttDeviceResponse instance;

        public MqttDeviceResponseTests()
        {
            // TODO uncomment below to create an instance of MqttDeviceResponse
            //instance = new MqttDeviceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MqttDeviceResponse
        /// </summary>
        [Fact]
        public void MqttDeviceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MqttDeviceResponse
            //Assert.IsType<MqttDeviceResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

    }

}
