/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing NewOrganisationTokenDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewOrganisationTokenDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewOrganisationTokenDto
        //private NewOrganisationTokenDto instance;

        public NewOrganisationTokenDtoTests()
        {
            // TODO uncomment below to create an instance of NewOrganisationTokenDto
            //instance = new NewOrganisationTokenDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewOrganisationTokenDto
        /// </summary>
        [Fact]
        public void NewOrganisationTokenDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewOrganisationTokenDto
            //Assert.IsType<NewOrganisationTokenDto>(instance);
        }


        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Fact]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }
        /// <summary>
        /// Test the property 'TokenName'
        /// </summary>
        [Fact]
        public void TokenNameTest()
        {
            // TODO unit test for the property 'TokenName'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Fact]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }
        /// <summary>
        /// Test the property 'AssignedUsers'
        /// </summary>
        [Fact]
        public void AssignedUsersTest()
        {
            // TODO unit test for the property 'AssignedUsers'
        }

    }

}
