/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing OrganisationPresetsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationPresetsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganisationPresetsDto
        //private OrganisationPresetsDto instance;

        public OrganisationPresetsDtoTests()
        {
            // TODO uncomment below to create an instance of OrganisationPresetsDto
            //instance = new OrganisationPresetsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganisationPresetsDto
        /// </summary>
        [Fact]
        public void OrganisationPresetsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganisationPresetsDto
            //Assert.IsType<OrganisationPresetsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PresetNumber'
        /// </summary>
        [Fact]
        public void PresetNumberTest()
        {
            // TODO unit test for the property 'PresetNumber'
        }
        /// <summary>
        /// Test the property 'PresetName'
        /// </summary>
        [Fact]
        public void PresetNameTest()
        {
            // TODO unit test for the property 'PresetName'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
        /// <summary>
        /// Test the property 'Ssid'
        /// </summary>
        [Fact]
        public void SsidTest()
        {
            // TODO unit test for the property 'Ssid'
        }

    }

}
