/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing OrganisationFollowing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationFollowingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganisationFollowing
        //private OrganisationFollowing instance;

        public OrganisationFollowingTests()
        {
            // TODO uncomment below to create an instance of OrganisationFollowing
            //instance = new OrganisationFollowing();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganisationFollowing
        /// </summary>
        [Fact]
        public void OrganisationFollowingInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganisationFollowing
            //Assert.IsType<OrganisationFollowing>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
        /// <summary>
        /// Test the property 'FollowName'
        /// </summary>
        [Fact]
        public void FollowNameTest()
        {
            // TODO unit test for the property 'FollowName'
        }
        /// <summary>
        /// Test the property 'SourceDevice'
        /// </summary>
        [Fact]
        public void SourceDeviceTest()
        {
            // TODO unit test for the property 'SourceDevice'
        }
        /// <summary>
        /// Test the property 'SourcePin'
        /// </summary>
        [Fact]
        public void SourcePinTest()
        {
            // TODO unit test for the property 'SourcePin'
        }
        /// <summary>
        /// Test the property 'DestinationDevice'
        /// </summary>
        [Fact]
        public void DestinationDeviceTest()
        {
            // TODO unit test for the property 'DestinationDevice'
        }
        /// <summary>
        /// Test the property 'DestinationPin'
        /// </summary>
        [Fact]
        public void DestinationPinTest()
        {
            // TODO unit test for the property 'DestinationPin'
        }
        /// <summary>
        /// Test the property 'Mirror'
        /// </summary>
        [Fact]
        public void MirrorTest()
        {
            // TODO unit test for the property 'Mirror'
        }

    }

}
