/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing OrganisationTenantDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationTenantDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganisationTenantDto
        //private OrganisationTenantDto instance;

        public OrganisationTenantDtoTests()
        {
            // TODO uncomment below to create an instance of OrganisationTenantDto
            //instance = new OrganisationTenantDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganisationTenantDto
        /// </summary>
        [Fact]
        public void OrganisationTenantDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganisationTenantDto
            //Assert.IsType<OrganisationTenantDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OrganisationNumber'
        /// </summary>
        [Fact]
        public void OrganisationNumberTest()
        {
            // TODO unit test for the property 'OrganisationNumber'
        }
        /// <summary>
        /// Test the property 'OrganisationName'
        /// </summary>
        [Fact]
        public void OrganisationNameTest()
        {
            // TODO unit test for the property 'OrganisationName'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'IsBusiness'
        /// </summary>
        [Fact]
        public void IsBusinessTest()
        {
            // TODO unit test for the property 'IsBusiness'
        }
        /// <summary>
        /// Test the property 'TrialUsed'
        /// </summary>
        [Fact]
        public void TrialUsedTest()
        {
            // TODO unit test for the property 'TrialUsed'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

    }

}
