/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing PatchGateway
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchGatewayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchGateway
        //private PatchGateway instance;

        public PatchGatewayTests()
        {
            // TODO uncomment below to create an instance of PatchGateway
            //instance = new PatchGateway();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchGateway
        /// </summary>
        [Fact]
        public void PatchGatewayInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchGateway
            //Assert.IsType<PatchGateway>(instance);
        }


        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

    }

}
