/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing PatchDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchDeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchDevice
        //private PatchDevice instance;

        public PatchDeviceTests()
        {
            // TODO uncomment below to create an instance of PatchDevice
            //instance = new PatchDevice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchDevice
        /// </summary>
        [Fact]
        public void PatchDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchDevice
            //Assert.IsType<PatchDevice>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Support'
        /// </summary>
        [Fact]
        public void SupportTest()
        {
            // TODO unit test for the property 'Support'
        }

    }

}
