/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing PatchUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchUserRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchUserRequest
        //private PatchUserRequest instance;

        public PatchUserRequestTests()
        {
            // TODO uncomment below to create an instance of PatchUserRequest
            //instance = new PatchUserRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchUserRequest
        /// </summary>
        [Fact]
        public void PatchUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchUserRequest
            //Assert.IsType<PatchUserRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Forename'
        /// </summary>
        [Fact]
        public void ForenameTest()
        {
            // TODO unit test for the property 'Forename'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'Marketing'
        /// </summary>
        [Fact]
        public void MarketingTest()
        {
            // TODO unit test for the property 'Marketing'
        }
        /// <summary>
        /// Test the property 'DefaultOrganisation'
        /// </summary>
        [Fact]
        public void DefaultOrganisationTest()
        {
            // TODO unit test for the property 'DefaultOrganisation'
        }

    }

}
