/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing RegisterUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisterUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisterUserDto
        //private RegisterUserDto instance;

        public RegisterUserDtoTests()
        {
            // TODO uncomment below to create an instance of RegisterUserDto
            //instance = new RegisterUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisterUserDto
        /// </summary>
        [Fact]
        public void RegisterUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisterUserDto
            //Assert.IsType<RegisterUserDto>(instance);
        }


        /// <summary>
        /// Test the property 'Forename'
        /// </summary>
        [Fact]
        public void ForenameTest()
        {
            // TODO unit test for the property 'Forename'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'UserHandle'
        /// </summary>
        [Fact]
        public void UserHandleTest()
        {
            // TODO unit test for the property 'UserHandle'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Marketing'
        /// </summary>
        [Fact]
        public void MarketingTest()
        {
            // TODO unit test for the property 'Marketing'
        }

    }

}
