/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing RegiserTenantDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegiserTenantDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegiserTenantDto
        //private RegiserTenantDto instance;

        public RegiserTenantDtoTests()
        {
            // TODO uncomment below to create an instance of RegiserTenantDto
            //instance = new RegiserTenantDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegiserTenantDto
        /// </summary>
        [Fact]
        public void RegiserTenantDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegiserTenantDto
            //Assert.IsType<RegiserTenantDto>(instance);
        }


        /// <summary>
        /// Test the property 'OrganisationName'
        /// </summary>
        [Fact]
        public void OrganisationNameTest()
        {
            // TODO unit test for the property 'OrganisationName'
        }
        /// <summary>
        /// Test the property 'OrganisationHandle'
        /// </summary>
        [Fact]
        public void OrganisationHandleTest()
        {
            // TODO unit test for the property 'OrganisationHandle'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Fact]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Fact]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'IsBusiness'
        /// </summary>
        [Fact]
        public void IsBusinessTest()
        {
            // TODO unit test for the property 'IsBusiness'
        }
        /// <summary>
        /// Test the property 'PartnerId'
        /// </summary>
        [Fact]
        public void PartnerIdTest()
        {
            // TODO unit test for the property 'PartnerId'
        }
        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Fact]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }
        /// <summary>
        /// Test the property 'CustomerForename'
        /// </summary>
        [Fact]
        public void CustomerForenameTest()
        {
            // TODO unit test for the property 'CustomerForename'
        }
        /// <summary>
        /// Test the property 'CustomerSurname'
        /// </summary>
        [Fact]
        public void CustomerSurnameTest()
        {
            // TODO unit test for the property 'CustomerSurname'
        }

    }

}
