/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing RegisterOrganisationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisterOrganisationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisterOrganisationResult
        //private RegisterOrganisationResult instance;

        public RegisterOrganisationResultTests()
        {
            // TODO uncomment below to create an instance of RegisterOrganisationResult
            //instance = new RegisterOrganisationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisterOrganisationResult
        /// </summary>
        [Fact]
        public void RegisterOrganisationResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisterOrganisationResult
            //Assert.IsType<RegisterOrganisationResult>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'OrganisationNumber'
        /// </summary>
        [Fact]
        public void OrganisationNumberTest()
        {
            // TODO unit test for the property 'OrganisationNumber'
        }

    }

}
