/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing UartSetup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UartSetupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UartSetup
        //private UartSetup instance;

        public UartSetupTests()
        {
            // TODO uncomment below to create an instance of UartSetup
            //instance = new UartSetup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UartSetup
        /// </summary>
        [Fact]
        public void UartSetupInstanceTest()
        {
            // TODO uncomment below to test "IsType" UartSetup
            //Assert.IsType<UartSetup>(instance);
        }


        /// <summary>
        /// Test the property 'Baudrate'
        /// </summary>
        [Fact]
        public void BaudrateTest()
        {
            // TODO unit test for the property 'Baudrate'
        }
        /// <summary>
        /// Test the property 'Databits'
        /// </summary>
        [Fact]
        public void DatabitsTest()
        {
            // TODO unit test for the property 'Databits'
        }
        /// <summary>
        /// Test the property 'Parity'
        /// </summary>
        [Fact]
        public void ParityTest()
        {
            // TODO unit test for the property 'Parity'
        }
        /// <summary>
        /// Test the property 'Stopbits'
        /// </summary>
        [Fact]
        public void StopbitsTest()
        {
            // TODO unit test for the property 'Stopbits'
        }

    }

}
