/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateResponse
        //private UpdateResponse instance;

        public UpdateResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateResponse
            //instance = new UpdateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateResponse
        /// </summary>
        [Fact]
        public void UpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateResponse
            //Assert.IsType<UpdateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SuccessfulDevices'
        /// </summary>
        [Fact]
        public void SuccessfulDevicesTest()
        {
            // TODO unit test for the property 'SuccessfulDevices'
        }
        /// <summary>
        /// Test the property 'FailedDevices'
        /// </summary>
        [Fact]
        public void FailedDevicesTest()
        {
            // TODO unit test for the property 'FailedDevices'
        }

    }

}
