/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing VyneNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VyneNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VyneNode
        //private VyneNode instance;

        public VyneNodeTests()
        {
            // TODO uncomment below to create an instance of VyneNode
            //instance = new VyneNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VyneNode
        /// </summary>
        [Fact]
        public void VyneNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" VyneNode
            //Assert.IsType<VyneNode>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Fact]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }
        /// <summary>
        /// Test the property 'FirstSeen'
        /// </summary>
        [Fact]
        public void FirstSeenTest()
        {
            // TODO unit test for the property 'FirstSeen'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'Enable'
        /// </summary>
        [Fact]
        public void EnableTest()
        {
            // TODO unit test for the property 'Enable'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Setup'
        /// </summary>
        [Fact]
        public void SetupTest()
        {
            // TODO unit test for the property 'Setup'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Power'
        /// </summary>
        [Fact]
        public void PowerTest()
        {
            // TODO unit test for the property 'Power'
        }
        /// <summary>
        /// Test the property 'Identify'
        /// </summary>
        [Fact]
        public void IdentifyTest()
        {
            // TODO unit test for the property 'Identify'
        }
        /// <summary>
        /// Test the property 'Pin'
        /// </summary>
        [Fact]
        public void PinTest()
        {
            // TODO unit test for the property 'Pin'
        }

    }

}
