/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookStatus
        //private WebhookStatus instance;

        public WebhookStatusTests()
        {
            // TODO uncomment below to create an instance of WebhookStatus
            //instance = new WebhookStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookStatus
        /// </summary>
        [Fact]
        public void WebhookStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookStatus
            //Assert.IsType<WebhookStatus>(instance);
        }



    }

}
