/*
 * Fingoti API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fingoti.Api;
using Fingoti.Model;
using Fingoti.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fingoti.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookAttempts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookAttemptsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookAttempts
        //private WebhookAttempts instance;

        public WebhookAttemptsTests()
        {
            // TODO uncomment below to create an instance of WebhookAttempts
            //instance = new WebhookAttempts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookAttempts
        /// </summary>
        [Fact]
        public void WebhookAttemptsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookAttempts
            //Assert.IsType<WebhookAttempts>(instance);
        }


        /// <summary>
        /// Test the property 'Attempt'
        /// </summary>
        [Fact]
        public void AttemptTest()
        {
            // TODO unit test for the property 'Attempt'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Fact]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }
        /// <summary>
        /// Test the property 'ResponseDescription'
        /// </summary>
        [Fact]
        public void ResponseDescriptionTest()
        {
            // TODO unit test for the property 'ResponseDescription'
        }
        /// <summary>
        /// Test the property 'ResponseHeaders'
        /// </summary>
        [Fact]
        public void ResponseHeadersTest()
        {
            // TODO unit test for the property 'ResponseHeaders'
        }
        /// <summary>
        /// Test the property 'ResponseBody'
        /// </summary>
        [Fact]
        public void ResponseBodyTest()
        {
            // TODO unit test for the property 'ResponseBody'
        }

    }

}
